### ISSUE TITLE
Make a List of Organizations

### ISSUE THREAD

**Issue by anubhav217** [Sparsh1212/gsocanalyzer#18]

**Comment by BashCache** [comment]
Hi, I have few doubts regarding this. Are we supposed to scrape the data and give the list of organizations that participate in GSoC. If so, I would like to contribute

**Comment by Sparsh1212** [comment]
Hi @BashCache, yes! you got it right.
Actually, we want to make the search more effective, so for that, we need a json list of all the organizations and then use that json file to integrate it in the search filter of "Search by organizations", so that the users can get search suggestions while searching. I'll be opening up a separate complete issue for this, and will close this one. Let me know if you would like to work on the complete task.
