### ISSUE TITLE
Stacking the organizational cards horizontally in pc view instead of vertically

### ISSUE THREAD

**Issue by Soumadipdas18** [Sparsh1212/gsocanalyzer#52]
We can stack the cards horizontally in pc view, so that the user need not scroll, to view each card. In vertical view, the user needs to scroll, it is difficult to compare the stats of two or more cards

**Comment by Soumadipdas18** [comment]
if its genuine, can I work on this?

**Comment by Sparsh1212** [comment]
Can you please elaborate more on what you are suggesting? Are you suggesting a carousel view that will have a horizontal scroll or do we just wrap the cards? Suppose we display 3 cards in a row and then the remaining cards are rendered onto the next row.

**Comment by Soumadipdas18** [comment]
Yes we can display 4-5 cards in a row, and the others in the next row

**Comment by Sparsh1212** [comment]
Okay sounds reasonable to me. Instead of 4-5, it's better to render 3 cards at a time. Also, we need to reduce the size of cards by a bit. I am currently blocking the points for this issue, as I am not sure how it will look in the new design. So, feel free to work on this. If the UI/UX looks decent enough, you will be awarded points for both the issue and the PR.

**Comment by Soumadipdas18** [comment]
Ok

**Comment by Sparsh1212** [comment]
@Soumadipdas18 Any update on this?

**Comment by iamrahulrnair** [comment]
Tag me , i can work on this 😃

**Comment by iamrahulrnair** [comment]
The ui may look ugly since different cards have different sizes, this feature will be good if considering a major ui change for statistic
<hr>

![Screenshot from 2021-12-13 21-14-54](https://user-images.githubusercontent.com/55950758/145843229-f9474aea-c07e-44d7-875f-a9ba5fc93f3f.png)
![Screenshot from 2021-12-13 21-14-57](https://user-images.githubusercontent.com/55950758/145843220-772df19f-d9d4-4e39-9024-0c6309b8a6b9.png)
![Screenshot from 2021-12-13 21-15-01](https://user-images.githubusercontent.com/55950758/145843208-2a67181d-50ec-429b-9af8-0b666c4eea84.png)

**Comment by Sparsh1212** [comment]
> The ui may look ugly since different cards have different sizes, this feature will be good if considering a major ui change for statistic
> 
> ![Screenshot from 2021-12-13 21-14-54](https://user-images.githubusercontent.com/55950758/145843229-f9474aea-c07e-44d7-875f-a9ba5fc93f3f.png) ![Screenshot from 2021-12-13 21-14-57](https://user-images.githubusercontent.com/55950758/145843220-772df19f-d9d4-4e39-9024-0c6309b8a6b9.png) ![Screenshot from 2021-12-13 21-15-01](https://user-images.githubusercontent.com/55950758/145843208-2a67181d-50ec-429b-9af8-0b666c4eea84.png)

I see, this doesn't look good. So, looks like, we'll have to close this issue as of now. However, based on your efforts you will be awarded 3 points for the experiment.

**Comment by iamrahulrnair** [comment]
thanks man, could u brief about the points since am new to this, and thanks :-)

**Comment by Sparsh1212** [comment]
> thanks man, could u brief about the points since am new to this, and thanks :-)

Sure! The points are as follows:
1 for a very easy fix
5 for easy fix
10 for medium fix
15 for hard fix

Since yours was between very easy and easy, so I decided to go with 3.
